version: "3"
services:
    mail:
        build:
            context: public/mail
            dockerfile: Dockerfile
        networks:
            public:
                ipv4_address: 192.168.30.2
        dns:
            - "192.168.30.3:49700"
        volumes:
            - ssl_private:/etc/ssl/private
            - ssl_certs:/etc/ssl/certs
        ports:
            - "25:25"
            - "110:110"
            - "143:143"
            - "465:465"
            - "783:783"
            - "995:995"
            - "587:587"

    # dns:
    #     build:
    #         context: intranet/DNS
    #         dockerfile: Dockerfile
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.3
    #     dns: 192.168.20.3
    #     ports:
    #     - "5353:53"


    # nginx:
    #     image: nginx:1.23.3
    #     ports:
    #         - 80:80
    #     volumes:
    #         - ./web/src:/var/www/php
    #         - ./web/.docker/nginx/conf.d:/etc/nginx/conf.d
    #     depends_on:
    #         - php
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.4
    #     dns: 192.168.20.3

    # pc:
    #     build:
    #         context: intranet/pc
    #         dockerfile: Dockerfile
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.5
    #     dns: 192.168.20.3

    # pc2:
    #     build:
    #         context: intranet/pc
    #         dockerfile: Dockerfile
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.6
    #     dns: 192.168.20.3

    # php:
    #     build: intranet/web/.docker/php
    #     working_dir: /var/www/php
    #     volumes:
    #         - ./web/src:/var/www/php
    #     depends_on:
    #         mysql:
    #             condition: service_healthy
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.11
    #     dns: 192.168.20.3:5353

    # mysql:
    #     image: mysql/mysql-server:8.0
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_ROOT_HOST: "%"
    #         MYSQL_DATABASE: demo
    #     volumes:
    #         - ./web/.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - mysqldata:/var/lib/mysql
    #     healthcheck:
    #         test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    #         interval: 5s
    #         retries: 10
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.12
    #     dns: 192.168.20.3

    dns:
        build:
            context: public/dns/resolver/
            dockerfile: Dockerfile
        networks:
            public:
                ipv4_address: 192.168.30.3
        dns:
            - "192.168.30.3:49700"
        ports:
            - "49700:53"

    soa:
        build:
            context: public/dns/soa/
            dockerfile: Dockerfile
        networks:
            public:
                ipv4_address: 192.168.30.5
        dns:
          - "192.168.30.3:49700"
        ports:
          - "5300:53/udp"

    # mail_public:
    #     build:
    #         context: public/mail
    #         dockerfile: Dockerfile
    #     volumes:
    #         - ssl_private:/etc/ssl/private
    #         - ssl_certs:/etc/ssl/certs
    #     networks:
    #         public:
    #             ipv4_address: 192.168.30.2
    #     dns: 192.168.30.3:5300
        # ports:
        #     - "2525:25"
        #     - "1100:110"
        #     - "1430:143"
        #     - "4650:465"
        #     - "7830:783"
        #     - "9950:995"
        #     - "5870:587"

    pc_public:
        build:
            context: public/pc
            dockerfile: Dockerfile
        networks:
            public:
                ipv4_address: 192.168.30.6
        dns:
            - "192.168.30.3:49700"

volumes:
    ssl_private:
    ssl_certs:
    mysqldata:
networks:
    intranet:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.20.0/24
    public:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.30.0/24
                                                            
