version: "3"
services:
    mail:
        build:
            context: public/mail
            dockerfile: Dockerfile
        networks:
            public:
                ipv4_address: 192.168.30.2
        dns:
            - "192.168.30.5:53"
        volumes:
            - ssl_private:/etc/ssl/private
            - ssl_certs:/etc/ssl/certs
        ports:
            - "25:25"
            - "110:110"
            - "143:143"
            - "465:465"
            - "783:783"
            - "995:995"
            - "993:993"
            - "587:587"

    # nginx:
    #     image: nginx:1.23.3
    #     ports:
    #         - 80:80
    #     volumes:
    #         - ./web/src:/var/www/php
    #         - ./web/.docker/nginx/conf.d:/etc/nginx/conf.d
    #     depends_on:
    #         - php
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.4
    #     dns: 192.168.20.3

    # php:
    #     build: intranet/web/.docker/php
    #     working_dir: /var/www/php
    #     volumes:
    #         - ./web/src:/var/www/php
    #     depends_on:
    #         mysql:
    #             condition: service_healthy
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.11
    #     dns: 192.168.20.3:5353

    # mysql:
    #     image: mysql/mysql-server:8.0
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_ROOT_HOST: "%"
    #         MYSQL_DATABASE: demo
    #     volumes:
    #         - ./web/.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - mysqldata:/var/lib/mysql
    #     healthcheck:
    #         test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    #         interval: 5s
    #         retries: 10
    #     networks:
    #         intranet:
    #             ipv4_address: 192.168.20.12
    #     dns: 192.168.20.3

    soa:
        build:
            context: public/dns/soa/
            dockerfile: Dockerfile
        networks:
            public:
                ipv4_address: 192.168.30.5
        ports:
          - "53:53/udp"
          - "53:53/tcp"

    pc_public:
        build:
            context: public/pc
            dockerfile: Dockerfile
        networks:
            public:
                ipv4_address: 192.168.30.6
        dns:
            - "192.168.30.5:53"

volumes:
    ssl_private:
    ssl_certs:
    mysqldata:
networks:
    #intranet:
    #    driver: bridge
    #    ipam:
    #        config:
    #            - subnet: 192.168.20.0/24
    public:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.30.0/24
