version: "3" 
name: woodytoys
services:
  web:
    image: nginx 
    links:
      - db:database
    ports:
      - 80:80
      - 443:443
    networks:
      - private-net
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private-net
  dns:
    image: ubuntu/bind9
    ports:
      - 53:53/udp
      - 53:53
    networks:
      - private-net
  soa:
    image: ubuntu/bind9
    ports:
      - 53:53/udp
      - 53:53
    networks:
      - private-net
  mail:
    image: postfix:latest
    hostname: mail.example.com
    volumes:
      - ./postfix/main.cf:/etc/postfix/main.cf
      - ./postfix/virtual:/etc/postfix/virtual
    ports:
      - 25:25
    networks:
      - private-net
  imap:
    image: dovecot:latest
    volumes:
      - ./dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./dovecot/users:/etc/dovecot/users
      - maildata:/var/mail
    ports:
      - 993:993
    networks:
      - private-net
networks:
  private-net:
volumes:
  db-data:
  maildata:
