version: '3'

services:
  pc:
    build:
      context: pc/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.20.5
    dns:
      - 192.168.20.3

  mail:
    build:
      context: mail/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.20.2
    dns:
      - 192.168.20.3
  
  dns:
    build: 
      context: DNS/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.20.3
    dns:
      - 192.168.20.3

  # web:
  #   build:
  #   volumes:
  #     - ./web:/usr/share/nginx/html
  #   ports:
  #     - "80:80"
  #   networks:
  #     intranet:
  #       ipv4_address: 192.168.20.4

networks:
  intranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/16
        