version: '3'

services:
  mailserver:
    image: tvial/docker-mailserver
    container_name: mailserver
    hostname: mail.woodytoys.lab
    domainname: woodytoys.lab
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config:/tmp/docker-mailserver
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTGREY=1
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
      - MAIL_HOSTNAME=mail.woodytoys.lab
      - MAIL_DOMAIN=woodytoys.lab


volumes:
  maildata:
  mailstate:
  maillogs:
